name: debug shell
on:
  workflow_dispatch:
    inputs:
      uhost:
      uport:
        default: 9797
      lport:
        default: 9798
      extra:
        default: whatever
jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: fscarmen/warp-on-actions@v1.0
      - uses: actions/checkout@v4
      - name: shell
        run: |
          uhost=$(jq -r .inputs.uhost "$GITHUB_EVENT_PATH")
          uport=$(jq -r .inputs.uport "$GITHUB_EVENT_PATH")
          lport=$(jq -r .inputs.lport "$GITHUB_EVENT_PATH")
          echo "::add-mask::$uhost" "::add-mask::$uport" "::add-mask::$lport"
          id 
          echo addr ---------------------
          ip addr || :
          echo link ---------------------
          ip link || :
          echo key ----------------------
          cat ssh/key.pub
          echo route --------------------
          ip -o route get 2a00:: || :
          ip -o route get 1.1.1.1 || :
          while sleep 30 && [ -r latch ]; do :; done
          pkill -P $$
          echo DONE
          :
      - uses: actions/upload-artifact@v4
        with: {name: foo, path: foo}

