name: debug shell ver 2
on:
  workflow_dispatch:
    inputs:
      port:
        default: 9797
jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - name: warp
        uses: fscarmen/warp-on-actions@v1.2
      - name: sshd
        run: |
          mkdir -m 0700 ssh
          ssh-keygen -qN '' -f ssh/srv-key
          printf '%s' '${{secrets.SSH_PUBKEY}}' > ssh/cli-key.pub
          /usr/sbin/sshd -o PidFile=none -f /dev/null -De -p 9797 \
            -o "AuthorizedKeysFile=$(pwd)/ssh/cli-key.pub" \
            -h "$(pwd)/ssh/srv-key" &
          echo link ---------------------
          ip link
          echo addr ---------------------
          ip addr
          echo ------------------
          id
          pwd
          ls
          while sleep 180 && [ -r latch ]; do :; done
          pkill -P $$
          echo DONE
