on:
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/solaris-vm@main
        with:
          run: |
            pwd
            ls -ahl
            id
            set
            sleep 60
