name: test-output
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          i=0; while [ "$i" -lt 30 ]; do date "+$i%t%H:%M:%S"; i=$((i+1)); sleep 1; done
          echo DONE

