name: Autoreconf
on:
  workflow_dispatch:
    inputs:
      cmd:
        type: string
        default: touch CONFIGURED
jobs:
  auto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: auto
        run: |
          set -ex
          user=${{github.repository_owner}}
          email=$(git log -n1 --author="$user" --format=format:%ae)
          git config user.name "$user[sync]"
          git config user.email "${email:-actions@github.com}"
          git checkout -b main-auto
          ${{inputs.cmd}}
          git add -f .
          git diff --cached --quiet ||
            git commit -m "[auto] $(git show --quiet --pretty=format:%s)"
          git push -f -u origin HEAD
